print("Podaj pierwszą liczbę")
liczba1 = input()
print("Podaj drugą liczbę")
liczba2 = input ()
wynik = int(liczba1)+int(liczba2)
print(f"Wynikiem dodawania tych liczb jest: {wynik}")
wynik2 = int(liczba1)-int(liczba2)
print(f"Wynikiem odejmowania tych liczb jest: {wynik2}")
wynik3 = int(liczba1)*int(liczba2)
print(f"Wynikiem mnożenia tych liczb jest: {wynik3}")
wynik4 = int(liczba1)/int(liczba2)
print(f"Wynikiem dzielenia tych liczb jest: {wynik4}")
